# Live Message Update Config
msgRefreshRate:
  # In seconds
  mcStatusRefreshInterval: 2
  mcStatusRefreshDuration: 900

# REST API Server Config
apiServer:
  serverHostName: 'localhost'

# Minecraft Server Config
mcServer:
  mcServerSelections:
  - 'Survival World'
  - 'Creative World'
  mcServerSelectionDescs:
  - 'Forge with friends'
  - 'Testing world'
  mcServerAliases:
  - 'survival-world'
  - 'creative-world'
  mcServerAddr: 
  - 'play1.addr.mc'
  - 'play2.addr.mc'
  serverStart:
    # In seconds
    delay: 10
    mcStartPingInterval: 5
    mcStartPingDuration: 180
