# Live Message Update Config
msgRefreshRate:
  # In seconds
  mcStatusRefreshInterval: 2
  mcStatusRefreshDuration: 900

# REST API Server Config
apiServer:
  serverHostName: 'localhost'

# Minecraft Server Config
mcServer:
  mcServerAddr: 'play.addr.mc'
  serverStart:
    # In seconds
    delay: 10
    mcStartPingInterval: 5
    mcStartPingDuration: 180
